swagger: '2.0'
info:
  title: Praxeum API
  version: '1.0'
  description: >-
    This API makes working with technical profiles from the Microsoft Learning
    portal easy-peasy.
host: glr-praxeum-apimgmt.azure-api.net
basePath: /learners
schemes:
  - https
securityDefinitions:
  apiKeyHeader:
    type: apiKey
    name: Ocp-Apim-Subscription-Key
    in: header
  apiKeyQuery:
    type: apiKey
    name: subscription-key
    in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
paths:
  /learners:
    get:
      description: Return a Microsoft user profile.
      operationId: get-microsoftprofilehttptrigger
      summary: Return a Microsoft user profile.
      parameters:
        - name: name
          in: query
          description: The upn of the Microsoft user profile
          type: string
      parameters:
        - name: forceRefresh
          in: query
          description: Flag to force a refresh of the Microsoft user profile
          type: string
      responses:
        '200':
          description: Successfully returns a Microsoft user profile.
          examples:
            application/json:
              displayName: Malcolm Reynolds
              userPrincipalName: null
              userName: malreynolds
              hasSeenMicrosoftPrivacyNotice: true
              progressStatus:
                totalPoints: 5299
                currentLevel: 4
                currentLevelPointsEarned: 100
                badgesEarned: 5
                trophiesEarned: 0
              achievements:
                - title: Browncoats 101
                  type: badge
                  url: >-
                    https://docs.microsoft.com/en-us/learn/modules/build-cosmos-db-app-with-vscode
                  image: >-
                    https://docs.microsoft.com/en-us/learn/achievements/build-cosmos-db-app-with-vscode.svg
                  achievedDate: '2018-12-10T00:00:00'
                - title: How to pilot a Firefly class ship
                  type: badge
                  url: >-
                    https://docs.microsoft.com/en-us/learn/modules/create-cosmos-db-for-scale
                  image: >-
                    https://docs.microsoft.com/en-us/learn/achievements/create-cosmos-db-for-scale.svg
                  achievedDate: '2018-12-10T00:00:00'
              createdOn: '2018-10-03T00:00:00'
      produces:
        - application/json
tags: []
